### ISSUE TITLE
[Feat] BottomNavigation 구현

### ISSUE THREAD

**Issue by nahy-512** [nahy-512/Toss_clone_coding#1]
![image](https://github.com/nahy-512/Toss_clone_coding/assets/101113025/93b0dfce-b2f7-4dce-a5ef-53dd658cb29b)

## Description
Toss의 BottomNavigation을 구현한다.

## To-do
- [x] BottomNavigation 아이콘 추가
- [ ] BottomNavigation 상단 모서리 둥글게
- [x] 아이템 클릭 시 화면 이동
- [ ] 아이템 클릭 시 색 변경
- [ ] 다크모드 대응
